/*
 * Rest_API_Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Error;
import io.swagger.client.model.Event;
import io.swagger.client.model.Events;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for EventApi
 */
@Ignore
public class EventApiTest {

    private final EventApi api = new EventApi();

    /**
     * DeleteEvent
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteEventTest() throws Exception {
        String id = null;
        String response = api.deleteEvent(id);

        // TODO: test validations
    }
    /**
     * Get_ALL_Event
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllEventTest() throws Exception {
        Events response = api.getAllEvent();

        // TODO: test validations
    }
    /**
     * UpdateEvent
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateEventTest() throws Exception {
        Event body = null;
        String response = api.updateEvent(body);

        // TODO: test validations
    }
}
