/*
 * Rest_API_Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Error;
import io.swagger.client.model.Files;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for FileApi
 */
@Ignore
public class FileApiTest {

    private final FileApi api = new FileApi();

    /**
     * CreteFile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createFileTest() throws Exception {
        java.io.File body = null;
        String response = api.createFile(body);

        // TODO: test validations
    }
    /**
     * DeleteFile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteFileTest() throws Exception {
        String id = null;
        String response = api.deleteFile(id);

        // TODO: test validations
    }
    /**
     * Get_ALL_File
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllFileTest() throws Exception {
        Files response = api.getAllFile();

        // TODO: test validations
    }
    /**
     * UpdateFile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateFileTest() throws Exception {
        java.io.File body = null;
        String response = api.updateFile(body);

        // TODO: test validations
    }
}
